spring:
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5678/linker-database
    username: myuser
    password: mypassword
retrofit:
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL}
jwt:
  secret-key: 512393ea8dee67633d7f1197c4938239f57c1a323a227e919977f0b478c5f5fd3a4dab07ba1a796297c5cd7c9519e6403ad2742e0c07024290aafa3d6f9f2424
linker:
  allowed-origins: "http://localhost:3000"
coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  sender-number: ${COOLSMS_SENDER_NUMBER}